name:                status-client
version:             0.1.0.0
github:              "thealmarty/status-client"
license:             BSD3
author:              "Marty Stumpf"
maintainer:          "thealmartyblog@gmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thealmarty/status-client#readme>

dependencies:
- base >= 4.7 && < 5
- text
- websockets
- mtl
- network

library:
  source-dirs: src
  

executables:
  status-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - OverloadedStrings
    dependencies:
    - status-client

tests:
  status-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - status-client
